preload = /home/loop/Descargas/aerial-shot-mountainous-landscape-covered-with-snow-foggy-day.jpg

wallpaper = eDP-1,/home/loop/Descargas/aerial-shot-mountainous-landscape-covered-with-snow-foggy-day.jpg

splash = false
