background {
    monitor =
    color = rgba(10, 10, 10, 1)
}

label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
    color = rgba(200, 200, 200, 1.0)
    font_size = 64
    font_family = monospace
    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%Y-%m-%d")"
    color = rgba(120, 120, 120, 1.0)
    font_size = 16
    font_family = monospace
    position = 0, -10
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 200, 40
    outline_thickness = 1
    dots_size = 0.2
    dots_spacing = 0.2
    outer_color = rgba(60, 60, 60, 1)
    inner_color = rgba(20, 20, 20, 1)
    font_color = rgba(200, 200, 200, 1)
    fade_on_empty = true
    placeholder_text = <i>contraseña</i>
    position = 0, -100
    halign = center
    valign = center
}
