monitor=,preferred,auto,1
$terminal = kitty
$fileManager = kitty -e yazi
$menu = wofi --show drun
exec-once = ~/.config/hypr/start.sh

input {
    kb_layout = es
    follow_mouse = 1
    touchpad {
        natural_scroll = yes
    }
}

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(aaaaaaff)
    col.inactive_border = rgba(444444ff)
}

layerrule = order 1, match:namespace waybar

decoration {
    rounding = 0
    blur {
        enabled = true
        size = 3
        passes = 1
    }
}

animations {
    enabled = yes
}

dwindle {
    pseudotile = yes
    preserve_split = yes
}

bind = SUPER, Return, exec, $terminal
bind = SUPER, Q, killactive
bind = SUPER, M, exit
bind = SUPER, E, exec, $fileManager
bind = SUPER, V, togglefloating
bind = SUPER, R, exec, $menu
bind = SUPER, F, fullscreen
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow
bind = , XF86AudioRaiseVolume, exec, swayosd-client --output-volume raise
bind = , XF86AudioLowerVolume, exec, swayosd-client --output-volume lower
bind = , XF86AudioMute, exec, swayosd-client --output-volume mute-toggle
bind = , Print, exec, grimblast copysave area ~/Imágenes/
bind = , Print, exec, grim -g "$(slurp)" ~/Imágenes/$(date +%Y%m%d_%H%M%S).png
bind = SHIFT, Print, exec, grim ~/Imágenes/$(date +%Y%m%d_%H%M%S).png
bind = SUPER, S, exec, ~/.config/hypr/shortcuts.sh